# Fetching the latest node image on alpine linux
FROM node:alpine AS development

ENV NODE_ENV development

WORKDIR /react-app

COPY ./package*.json /react-app

RUN npm install

COPY . .

# Starting our application
CMD ["npm","start"]